#!/usr/bin/env python3
"""
CSV → JSON pipeline: Generate web-optimized artefacts from consolidated cyclone data.

Run from the project root:
    python3 scripts/preprocess_data.py

Input:
    data/processed/tracks_south_atlantic_consolidated.csv
    (generated by: python scripts/data/run_pipeline.py)

Output:
    site/public/data/summary.json          — one entry per track (metadata + simplified line coords)
    site/public/data/details/{year}.json   — full timestep data per year, loaded on demand by the web app

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Data sources
------------
The consolidated CSV contains data from:
    - Cyclone tracks: Gramcianinov et al. (2019), Mendeley Data, DOI: 10.17632/kwcvfr52hp.4
    - LEC diagnostics: Zenodo, DOI: 10.5281/zenodo.18133432
    - Genesis regions: Gramcianinov et al. (2019), Climate Dynamics
    - Lifecycle phases: Cyclophaser (de Souza et al., JOSS 2025)

Genesis region classification
-----------------------------
The source data includes pre-computed region labels (ARG, LA-PLATA, SE-BR).
For display, these are mapped to more descriptive names.

Lifecycle phase labels
----------------------
Phase labels (incipient, intensification, mature, decay, etc.) are pre-computed
in the source dataset using the Cyclophaser tool:

    de Souza, D. C., da Dias, P. L. S., Gramcianinov, C. B., & de Camargo, R. (2025).
    Cyclophaser: A Python package for detecting extratropical cyclone life cycles.
    Journal of Open Source Software, 10(108), 7363.
    https://doi.org/10.21105/joss.07363

Temporal resolution note
------------------------
    - Track positions (lon, lat, vor42): 1-hourly
    - LEC energetics (Kz, Ke, Ck, Ca, etc.): 3-hourly (NaN at intermediate hours)

This is expected behavior. The JSON output omits NaN energetics values; the web
app displays "LEC diagnostics not available at this timestep" for those hours.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import pandas as pd
import numpy as np
import json
import math
from collections import Counter
from pathlib import Path
from datetime import datetime

# ─── Paths ────────────────────────────────────────────────────────────────────
# Script must be run from the project root (cyclone_monitor_south_atlantic/).
# Primary input: consolidated CSV generated by scripts/data/run_pipeline.py
INPUT_CSV_CONSOLIDATED = Path("data/processed/tracks_south_atlantic_consolidated.csv")
# Fallback input: legacy raw CSV (for backward compatibility)
INPUT_CSV_LEGACY = Path("data/raw/tracks_SAt_filtered_with_energetics.csv")
# Per-cyclone CPS classification (optional).
# PROVENANCE PLACEHOLDER: produced by paper_energy_patterns and copied by hand;
# no Zenodo DOI minted yet. See CPS_PARAMS_FILE in scripts/data/preprocess_data.py.
INPUT_CSV_CPS_CLASS = Path("data/raw/cps_classification_SAt.csv")
# Track-only cyclones from the raw tracking catalogue (optional).
# Generated by scripts/data/ingest_raw_catalogue.py. Only the COUNT is read
# here; the tracks themselves are exported by scripts/preprocess_raw_tracks.py.
# Consolidated per-cyclone base, built by scripts/data/merge_wind.py. Supplies
# the per-cyclone wind intensity for the wind display variables.
INPUT_PARQUET_CYCLONES = Path("data/processed/cyclones.parquet")
# Canonical provenance registry. Emitted to the site so the About page renders
# from it instead of hard-coding DOIs that then drift.
INPUT_SOURCES_JSON = Path("data/metadata/sources.json")
OUTPUT_DIR  = Path("site/public/data")
DETAILS_DIR = OUTPUT_DIR / "details"

# ─── Precision ────────────────────────────────────────────────────────────────
COORD_DECIMALS      = 2   # ~1 km — sufficient for trajectory visualisation
VOR42_DECIMALS      = 4
ENERGETICS_DECIMALS = 3
CPS_DECIMALS        = 2   # B in m, VTL/VTU dimensionless — 2 dp is ample
WIND_DECIMALS       = 2   # m s⁻¹ — matches what the interface renders
MAX_COORDS_PER_TRACK = 120

# ─── Region name mapping (source data uses short codes) ────────────────────────
# Canonical codes: ARG, LA-PLATA, SE-BR
# Based on cyclogenesis hotspots from Gramcianinov et al. (2019), Climate Dynamics
REGION_DISPLAY_NAMES = {
    "ARG": "Southeastern Argentina",
    "LA-PLATA": "La Plata River Discharge",
    "SE-BR": "Southeast Brazil",
}

# ─── CPS classification display names ─────────────────────────────────────────
# Per-cyclone structural classification from the Cyclone Phase Space.
# Codes come from cps_classification_SAt.csv → phase_class.
CPS_CLASS_LABELS = {
    "EC":           "Extratropical",
    "SC":           "Subtropical",
    "TC":           "Tropical",
    "ST":           "Subtropical transition (EC→SC)",
    "SD":           "Subtropical decay (SC→EC)",
    "TT":           "Tropical transition",
    "ET":           "Extratropical transition",
    "EC_like":      "Extratropical characteristics (not sustained 36 h)",
    "SC_like":      "Hybrid characteristics (not sustained 36 h)",
    "TC_like":      "Warm-core characteristics (not sustained 36 h)",
    "undetermined": "Undetermined",
    "no_cps_data":  "No CPS data",
}

# Grouping used by the type filter.
#
# TWO RULES, both learned the hard way:
#
#   1. A `*_like` class is NEVER grouped with the class it resembles. Those are
#      CHARACTERISTICS, not identifications: the structure was shown but never
#      sustained for the 36 h gate, and none of the identification guards
#      (genesis band, ocean, warm-seclusion test) was applied to it. Folding
#      `SC_like` into "Subtropical" asserts exactly what the classification
#      refuses to assert — and it is what put 548 unguarded cyclones, 68% of
#      them with genesis outside 20-40 S, under the "Subtropical" filter, plus
#      two `TC_like` at 44 S and 52 S under "Tropical".
#
#   2. Transitions are kept apart by TYPE. EC->SC and SC->EC are opposite
#      pathways and "Transition" hid that.
#
# The source of truth for rule 1 is the `class_kind` / `is_identified` columns of
# cps_classification_SAt.csv; this map must stay consistent with them.
CPS_CLASS_GROUPS = {
    "EC": "Extratropical",
    "SC": "Subtropical",
    "TC": "Tropical",
    "ST": "Subtropical transition",
    "SD": "Subtropical decay",
    "TT": "Tropical transition",
    "ET": "Extratropical transition",
    "EC_like": "Not sustained (<36 h)",
    "SC_like": "Not sustained (<36 h)",
    "TC_like": "Not sustained (<36 h)",
    "undetermined": "Undetermined",
    "no_cps_data": "No CPS data",
}

# Groups that represent an actual identification. The UI can use this to keep
# the descriptive groups visually and semantically separate from the identified
# ones.
CPS_IDENTIFIED_GROUPS = {
    "Extratropical", "Subtropical", "Tropical",
    "Subtropical transition", "Subtropical decay",
    "Tropical transition", "Extratropical transition",
}

# Number of histogram bins for the intensity distribution shown in the filter
# panel. 60 keeps the PDF smooth without bloating summary.json.
INTENSITY_PDF_BINS = 60

# ─── Display variables ────────────────────────────────────────────────────────
# The variables the user can colour the map by. The map's colour scale and the
# intensity filter both read the entry for whichever is active, which is what
# stops them from ever representing different quantities.
#
# The internal key 'vor42' is kept - it is the column name throughout the
# pipeline and the data files - but it is never shown: the interface calls it
# "Central relative vorticity".
#
# Wind intensity is the maximum, over all timesteps, of the largest of the four
# quadrant maxima at that height. That mirrors max_vor42 (the maximum of vor42
# over the track) exactly. It uses the 'max' statistic only: p99 stays a
# detailed per-quadrant diagnostic in the sidebar and never classifies a track.
DISPLAY_VARIABLES = {
    "vor42": {
        "label":       "Central relative vorticity",
        "short_label": "Vorticity",
        "unit":        "\u00d710\u207b\u2075 s\u207b\u00b9",
        "field":       "max_vor42",
        "decimals":    3,
    },
    "wind10": {
        "label":       "Wind 10 m",
        "short_label": "Wind 10 m",
        "unit":        "m s\u207b\u00b9",
        "field":       "max_wind10",
        "decimals":    2,
    },
    "wind100": {
        "label":       "Wind 100 m",
        "short_label": "Wind 100 m",
        "unit":        "m s\u207b\u00b9",
        "field":       "max_wind100",
        "decimals":    2,
    },
}


# ─── Genesis Region (fallback for legacy data without region column) ──────────
def assign_genesis_region_fallback(lat: float, lon: float) -> str:
    """
    Classify the cyclone genesis region from its first (genesis) position.
    
    This is a fallback for legacy data that doesn't have the pre-computed
    region column. The consolidated CSV already has region labels.

    Regions approximate the cyclogenesis hotspots identified in:
        Gramcianinov et al. (2019), Climate Dynamics, 53, 4115–4140.
    """
    if lon > 20:
        return "Indian Ocean / Other"
    if lon < -50 and lat < -45:
        return "Argentina / Patagonia"
    if -70 <= lon <= -48 and -45 <= lat <= -25:
        return "SE South America"
    if -55 <= lon <= -35 and -35 <= lat <= -20:
        return "SE Brazil Coast"
    if lon > -35 and -35 <= lat <= -20:
        return "Subtropical South Atlantic"
    if lon > -50 and lat < -45:
        return "Open South Atlantic"
    return "Open South Atlantic"


# ─── Lifecycle Phase (fallback for legacy data without period column) ─────────
def compute_phases_fallback(vor42_series: pd.Series) -> list:
    """
    Heuristic lifecycle phase labels derived from the track's vor42 time series.
    
    This is a fallback for legacy data that doesn't have the pre-computed
    period column. The consolidated CSV already has Cyclophaser phase labels.

    Phase definitions (heuristic approximation):
        incipient        : first 2 timesteps (system just forming)
        intensification  : vor42 increasing, below 85 % of track maximum
        mature           : vor42 ≥ 85 % of track maximum
        decay            : vor42 decreasing, below 85 % of track maximum after peak
        dissipation      : last 2 timesteps
    """
    values = vor42_series.values
    n      = len(values)
    max_v  = float(values.max())
    max_i  = int(np.argmax(values))
    thresh = 0.85 * max_v

    phases = []
    for i, v in enumerate(values):
        if i <= 1:
            phases.append("incipient")
        elif i >= n - 2:
            phases.append("dissipation")
        elif i <= max_i and v < thresh:
            phases.append("intensification")
        elif v >= thresh:
            phases.append("mature")
        else:
            phases.append("decay")
    return phases


# ─── Helpers ─────────────────────────────────────────────────────────────────
def safe_float(value, decimals: int = 3):
    if value is None:
        return None
    try:
        f = float(value)
        if math.isnan(f):
            return None
        return round(f, decimals)
    except (TypeError, ValueError):
        return None


def write_sources_markdown(registry: dict, path: Path) -> None:
    """
    Render data/SOURCES.md from the provenance registry.

    Generated rather than written by hand so the human-readable provenance and
    the machine-readable one cannot drift apart. Edit
    data/metadata/sources.json; this file follows.
    """
    L: list[str] = []
    L.append("<!-- GENERATED FILE — do not edit by hand.")
    L.append("     Source: data/metadata/sources.json")
    L.append("     Regenerate: python scripts/preprocess_data.py -->")
    L.append("")
    L.append("# Data provenance")
    L.append("")
    L.append("Every dataset behind the South Atlantic Cyclone Monitor, where it came")
    L.append("from, which monitor variables it supplies, and what the pipeline does to")
    L.append("it locally.")
    L.append("")
    L.append(f"_Generated {datetime.now():%Y-%m-%d %H:%M:%S}._")
    L.append("")

    def render(key: str, e: dict) -> None:
        L.append(f"## {e.get('name', key)}")
        L.append("")
        if e.get("authors"):
            authors = "; ".join(e["authors"])
            year = f" ({e['year']})" if e.get("year") else ""
            L.append(f"**Authors:** {authors}{year}  ")
        if e.get("orcid"):
            L.append(f"**ORCID:** {', '.join(e['orcid'])}  ")
        if e.get("affiliation"):
            L.append(f"**Affiliation:** {e['affiliation']}  ")
        if e.get("journal"):
            vol = f", {e['volume']}" if e.get("volume") else ""
            pg = f", {e['pages']}" if e.get("pages") else ""
            L.append(f"**Published in:** {e['journal']}{vol}{pg}  ")
        if e.get("repository"):
            L.append(f"**Repository:** {e['repository']}  ")
        if e.get("version"):
            L.append(f"**Version:** {e['version']}  ")
        if e.get("publication_date"):
            L.append(f"**Date:** {e['publication_date']}  ")
        if e.get("license"):
            L.append(f"**Licence:** {e['license']}  ")
        if e.get("doi"):
            L.append(f"**DOI:** [{e['doi']}](https://doi.org/{e['doi']})  ")
        elif e.get("pending"):
            L.append("**DOI:** _not minted yet._  ")
            if e.get("pending_note"):
                L.append(f"> {e['pending_note']}  ")
        elif e.get("url"):
            L.append(f"**URL:** <{e['url']}>  ")
        if e.get("md5"):
            L.append(f"**Archive MD5:** `{e['md5']}`  ")
        L.append("")

        if e.get("role"):
            L.append(f"{e['role']}")
            L.append("")
        if e.get("coverage"):
            L.append("**Coverage**")
            L.append("")
            for k, v in e["coverage"].items():
                L.append(f"- {k.replace('_', ' ')}: {v}")
            L.append("")
        if e.get("variables"):
            L.append("**Monitor variables from this source**")
            L.append("")
            for v in e["variables"]:
                L.append(f"- `{v}`")
            L.append("")
        if e.get("transforms"):
            L.append("**Local transformations**")
            L.append("")
            for t in e["transforms"]:
                L.append(f"- {t}")
            L.append("")
        if e.get("conventions"):
            L.append("**Conventions to respect**")
            L.append("")
            for c in e["conventions"]:
                L.append(f"- {c}")
            L.append("")

    for key, entry in registry.get("sources", {}).items():
        render(key, entry)

    extra = registry.get("additional_references", {})
    if extra:
        L.append("---")
        L.append("")
        L.append("## Further references")
        L.append("")
        for key, e in extra.items():
            authors = "; ".join(e.get("authors", []))
            year = e.get("year", "")
            vol = f", {e['volume']}" if e.get("volume") else ""
            pg = f", {e['pages']}" if e.get("pages") else ""
            doi = e.get("doi", "")
            L.append(
                f"- {authors} ({year}). *{e.get('name','')}*. "
                f"{e.get('journal','')}{vol}{pg}. "
                + (f"[{doi}](https://doi.org/{doi})" if doi else "")
            )
            if e.get("role"):
                L.append(f"  - {e['role']}")
        L.append("")

    path.write_text("\n".join(L))


def compute_thresholds(values: np.ndarray) -> dict:
    """Quantile thresholds for one display variable's track-level peaks.

    p10 and max bound the colour ramp; the rest draw the guide lines and the
    shortcut chips in the intensity filter. Computed per variable, never reused
    across variables - a threshold in x10^-5 s^-1 means nothing in m s^-1.
    """
    v = np.asarray(values, dtype="float64")
    v = v[np.isfinite(v)]
    return {
        "p10": float(np.quantile(v, 0.10)),
        "p25": float(np.quantile(v, 0.25)),
        "p50": float(np.quantile(v, 0.50)),
        "p75": float(np.quantile(v, 0.75)),
        "p90": float(np.quantile(v, 0.90)),
        "p95": float(np.quantile(v, 0.95)),
        "max": float(v.max()),
    }


def load_wind_intensity(path: Path) -> dict:
    """
    Per-cyclone wind intensity, read from the consolidated base.

    data/processed/cyclones.parquet is produced by scripts/data/merge_wind.py
    and already holds max_wind10 / max_wind100 computed the same way for every
    level. Reading it here rather than recomputing keeps a single definition of
    track intensity in the pipeline.

    Returns {track_id: {"max_wind10": float|None, "max_wind100": float|None}},
    or {} when the base has not been built - the site then simply offers the
    vorticity display variable alone.
    """
    if not path.exists():
        print(f"  ! Consolidated base not found: {path}")
        print("    Wind display variables will be unavailable.")
        print("    Build it with: python scripts/data/merge_wind.py")
        return {}

    cols = ["track_id", "max_wind10", "max_wind100"]
    df = pd.read_parquet(path, columns=cols)
    out = {}
    for r in df.itertuples(index=False):
        out[int(r.track_id)] = {
            "max_wind10":  None if pd.isna(r.max_wind10) else float(r.max_wind10),
            "max_wind100": None if pd.isna(r.max_wind100) else float(r.max_wind100),
        }
    n10 = sum(1 for v in out.values() if v["max_wind10"] is not None)
    n100 = sum(1 for v in out.values() if v["max_wind100"] is not None)
    print(f"  Wind intensity: {len(out):,} cyclones "
          f"({n10:,} with 10 m, {n100:,} with 100 m)")
    return out


def load_cps_classification(path: Path) -> dict:
    """
    Load the per-cyclone CPS classification, keyed by track_id.

    Returns {} when the file is absent — CPS is optional and the site degrades
    gracefully (the type filter simply reports no data).

    Each entry carries:
        cls        phase_class code (EC, SC, ST, ...)
        label      human-readable expansion
        group      coarse grouping for the filter UI
        seq        state_sequence, e.g. "EC->SC" (None when absent)
        warm_secl  True when the identification guards rejected at least one
                   run as a Shapiro–Keyser warm seclusion. This is NOT a
                   phase_class: it is a property of the rejected runs, exposed
                   separately because it is scientifically interesting on its own.
    """
    if not path.exists():
        print(f"  ⚠ CPS classification not found: {path}")
        print("    Cyclone type filter will be empty.")
        return {}

    df = pd.read_csv(path)
    print(f"  CPS classification: {len(df):,} cyclones")

    out = {}
    for _, r in df.iterrows():
        code = str(r.get("phase_class", "no_cps_data"))
        n_ws = r.get("n_warm_seclusions", 0)
        try:
            n_ws = float(n_ws)
        except (TypeError, ValueError):
            n_ws = 0.0
        seq = r.get("state_sequence")
        if isinstance(seq, float) and math.isnan(seq):
            seq = None
        group = CPS_CLASS_GROUPS.get(code, "Undetermined")
        out[int(r["track_id"])] = {
            "cls":       code,
            "label":     CPS_CLASS_LABELS.get(code, code),
            "group":     group,
            # Read from the export when present; the map is the fallback so an
            # older CSV still yields a correct flag.
            "identified": bool(r["is_identified"]) if "is_identified" in r
                          and pd.notna(r.get("is_identified"))
                          else group in CPS_IDENTIFIED_GROUPS,
            "seq":       str(seq) if seq is not None else None,
            "warm_secl": bool(n_ws and n_ws > 0),
        }
    return out


def build_intensity_pdf(values: np.ndarray, thresholds: dict) -> dict:
    """
    Histogram of one display variable's track-level peaks, for the filter's PDF.

    Returns bin edges, the normalised density, and raw counts. The density is a
    proper probability density (integrates to 1 over the value axis), so the
    curve is comparable regardless of bin count.
    """
    counts, edges = np.histogram(values, bins=INTENSITY_PDF_BINS)
    widths = np.diff(edges)
    total = counts.sum()
    density = (counts / total / widths) if total > 0 else np.zeros_like(counts, dtype=float)

    return {
        "bin_edges": [round(float(e), 4) for e in edges],
        "counts":    [int(c) for c in counts],
        "density":   [round(float(d), 6) for d in density],
        "min":       round(float(values.min()), 4),
        "max":       round(float(values.max()), 4),
        "n":         int(values.size),
        # Repeated here so the chart can draw quantile guide lines without
        # cross-referencing another object.
        "quantiles": {k: round(float(v), 4) for k, v in thresholds.items()},
    }


def downsample_coords(lons, lats, max_pts: int = MAX_COORDS_PER_TRACK):
    n = len(lons)
    if n <= max_pts:
        indices = list(range(n))
    else:
        step    = n / max_pts
        indices = [int(i * step) for i in range(max_pts)]
        if indices[-1] != n - 1:
            indices[-1] = n - 1
    return [
        [round(float(lons[i]), COORD_DECIMALS), round(float(lats[i]), COORD_DECIMALS)]
        for i in indices
    ]


# ─── Main ─────────────────────────────────────────────────────────────────────
def main():
    # Determine input file
    if INPUT_CSV_CONSOLIDATED.exists():
        input_csv = INPUT_CSV_CONSOLIDATED
        use_precomputed = True
        print(f"[{datetime.now():%H:%M:%S}] Using consolidated CSV: {input_csv}")
    elif INPUT_CSV_LEGACY.exists():
        input_csv = INPUT_CSV_LEGACY
        use_precomputed = False
        print(f"[{datetime.now():%H:%M:%S}] Using legacy CSV: {input_csv}")
        print("  ⚠ Note: Run 'python scripts/data/run_pipeline.py' for full data with regions/phases")
    else:
        print(f"✗ No input data found!")
        print(f"  Expected: {INPUT_CSV_CONSOLIDATED}")
        print(f"  Or:       {INPUT_CSV_LEGACY}")
        print(f"\nRun data pipeline first:")
        print(f"  python scripts/data/run_pipeline.py")
        return 1
    
    print(f"[{datetime.now():%H:%M:%S}] Reading {input_csv.name} …")
    df = pd.read_csv(input_csv, parse_dates=["date"])
    
    # Handle column names (consolidated has 'lon'/'lat', legacy has 'lon vor'/'lat vor')
    if "lon vor" in df.columns:
        df = df.rename(columns={"lon vor": "lon", "lat vor": "lat"})

    n_tracks = df["track_id"].nunique()
    print(f"  {len(df):,} rows | {n_tracks:,} unique tracks")
    print(f"  Pre-computed region/period: {'Yes' if use_precomputed and 'region' in df.columns else 'No'}")

    df["year"] = (df["track_id"] // 10000).astype(int)
    df = df.sort_values(["track_id", "date"]).reset_index(drop=True)

    # ── Per-cyclone wind intensity (from the consolidated base) ─────────────
    print("  Loading wind intensity …")
    wind_intensity = load_wind_intensity(INPUT_PARQUET_CYCLONES)

    # ── Per-cyclone CPS classification ──────────────────────────────────────
    print("  Loading CPS classification …")
    cps_class_map = load_cps_classification(INPUT_CSV_CPS_CLASS)

    # ── Processing level ─────────────────────────────────────────────────────
    # Every cyclone in the consolidated CSV is fully processed (it carries LEC,
    # lifecycle phases and a genesis region — the LEC computation is in fact the
    # filter that produced this catalogue).
    #
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    DETAILS_DIR.mkdir(parents=True, exist_ok=True)

    # ── Process tracks ───────────────────────────────────────────────────────
    print(f"  Processing {n_tracks:,} tracks …")
    summaries  = []
    year_data: dict = {}

    for i, (tid, grp) in enumerate(df.groupby("track_id", sort=False)):
        if i % 1000 == 0:
            print(f"    {i}/{n_tracks}")

        grp   = grp.reset_index(drop=True)
        first = grp.iloc[0]
        last  = grp.iloc[-1]
        year  = int(first["year"])
        n     = len(grp)

        genesis_lat = round(float(first["lat"]), COORD_DECIMALS)
        genesis_lon = round(float(first["lon"]), COORD_DECIMALS)
        lysis_lat   = round(float(last["lat"]),  COORD_DECIMALS)
        lysis_lon   = round(float(last["lon"]),  COORD_DECIMALS)

        start_dt      = first["date"]
        end_dt        = last["date"]
        genesis_month = int(start_dt.month)
        duration_h    = int((end_dt - start_dt).total_seconds() / 3600)

        # Get genesis region (use pre-computed if available)
        if use_precomputed and "region" in grp.columns:
            region_code = str(first["region"])
            genesis_region = REGION_DISPLAY_NAMES.get(region_code, region_code)
        else:
            genesis_region = assign_genesis_region_fallback(genesis_lat, genesis_lon)
        
        max_vor42      = float(grp["vor42"].max())
        coords         = downsample_coords(grp["lon"].tolist(), grp["lat"].tolist())

        wind_info = wind_intensity.get(int(tid), {})
        cps_info = cps_class_map.get(int(tid))

        entry = {
            "id":             int(tid),
            "year":           year,
            "month":          genesis_month,
            "start":          start_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "end":            end_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "duration_h":     duration_h,
            "genesis_lat":    genesis_lat,
            "genesis_lon":    genesis_lon,
            "lysis_lat":      lysis_lat,
            "lysis_lon":      lysis_lon,
            "genesis_region": genesis_region,
            "max_vor42":      round(max_vor42, VOR42_DECIMALS),
            "coords":         coords,
        }

        # Peak wind at each height. Omitted rather than null when absent, so a
        # cyclone without wind data simply has no value for that variable.
        for _wkey in ("max_wind10", "max_wind100"):
            _wv = wind_info.get(_wkey)
            if _wv is not None:
                entry[_wkey] = round(_wv, WIND_DECIMALS)

        if cps_info:
            entry["cps_class"] = cps_info["cls"]
            entry["cps_label"] = cps_info["label"]
            entry["cps_group"] = cps_info["group"]
            entry["cps_identified"] = cps_info["identified"]
            if cps_info["seq"]:
                entry["cps_seq"] = cps_info["seq"]
            if cps_info["warm_secl"]:
                entry["warm_seclusion"] = True

        summaries.append(entry)

        # Per-timestep data (loaded on demand via details/{year}.json)
        # Use pre-computed phases if available, otherwise compute heuristically
        if use_precomputed and "period" in grp.columns:
            phases = grp["period"].fillna("unknown").tolist()
        else:
            phases = compute_phases_fallback(grp["vor42"])
        
        timesteps = []
        for j, row in grp.iterrows():
            ts: dict = {
                "date":  row["date"].strftime("%Y-%m-%dT%H:%M:%S"),
                "lon":   round(float(row["lon"]),   COORD_DECIMALS),
                "lat":   round(float(row["lat"]),   COORD_DECIMALS),
                "vor42": round(float(row["vor42"]), VOR42_DECIMALS),
                "phase": phases[j - grp.index[0]],
            }
            # Include all available energetics columns
            has_lec = False
            for col in ["Az", "Ae", "Kz", "Ke", "Cz", "Ca", "Ck", "Ce",
                       "BAz", "BAe", "BKz", "BKe", "Gz", "Ge",
                       "RGz", "RGe", "RKz", "RKe"]:
                v = safe_float(row.get(col), ENERGETICS_DECIMALS)
                if v is not None:
                    ts[col] = v
                    has_lec = True
            # Provenance flag: True = original 3-hourly value, False = linearly interpolated.
            # Only included when LEC data is present at this timestep.
            if has_lec:
                raw = row.get("lec_original")
                if raw is not None and not (isinstance(raw, float) and math.isnan(raw)):
                    ts["lec_original"] = bool(raw)

            # ── Cyclone Phase Space ──────────────────────────────────────────
            # Emitted only when the phase-space parameters exist at this
            # timestep (original or interpolated). cps_original mirrors
            # lec_original: True = computed here, False = interpolated.
            cps_b = safe_float(row.get("cps_B"), CPS_DECIMALS)
            if cps_b is not None:
                ts["cps_B"] = cps_b
                ts["cps_VTL"] = safe_float(row.get("cps_VTL"), CPS_DECIMALS)
                ts["cps_VTU"] = safe_float(row.get("cps_VTU"), CPS_DECIMALS)
                cps_cls = row.get("cps_class")
                if isinstance(cps_cls, str):
                    ts["cps_class"] = cps_cls
                # The guarded view: the accepted persistent state covering this
                # timestep, empty when none. cps_class alone is the raw
                # threshold label and carries no persistence and no guards.
                cps_st = row.get("cps_state")
                if isinstance(cps_st, str) and cps_st:
                    ts["cps_state"] = cps_st
                size_km = safe_float(row.get("cps_size_km"), 1)
                if size_km is not None:
                    ts["cps_size_km"] = size_km
                cps_dir = safe_float(row.get("cps_dir"), 1)
                if cps_dir is not None:
                    ts["cps_dir"] = cps_dir
                raw_o = row.get("cps_original")
                if raw_o is not None and not (isinstance(raw_o, float) and math.isnan(raw_o)):
                    ts["cps_original"] = bool(raw_o)

            timesteps.append(ts)

        if year not in year_data:
            year_data[year] = {}
        year_data[year][str(int(tid))] = {"timesteps": timesteps}

    # ── Per-variable distributions ───────────────────────────────────────────
    # One threshold set and one PDF per display variable, computed from the
    # track-level peaks of that variable alone. The site's colour ramp and its
    # intensity filter both read the active variable's entry, so they can never
    # end up describing different quantities.
    print("\n  Computing per-variable intensity distributions …")
    display_variables = {}
    for var, meta in DISPLAY_VARIABLES.items():
        values = np.array(
            [s[meta["field"]] for s in summaries if s.get(meta["field"]) is not None],
            dtype="float64",
        )
        if values.size == 0:
            print(f"    {var:8s} — no data, variable omitted")
            continue
        thresholds = compute_thresholds(values)
        display_variables[var] = {
            **{k: meta[k] for k in ("label", "short_label", "unit", "field", "decimals")},
            "n": int(values.size),
            "quantile_thresholds": {k: round(v, 4) for k, v in thresholds.items()},
            "intensity_pdf": build_intensity_pdf(values, thresholds),
        }
        print(f"    {var:8s} n={values.size:,}  "
              f"p10={thresholds['p10']:.3f}  max={thresholds['max']:.3f}  "
              f"[{meta['unit']}]")

    # ── Provenance registry ──────────────────────────────────────────────────
    # Loaded from data/metadata/sources.json and passed through to the site, so
    # the About page renders the DOIs rather than restating them.
    sources_registry = {}
    if INPUT_SOURCES_JSON.exists():
        with open(INPUT_SOURCES_JSON) as f:
            registry = json.load(f)
        sources_registry = {k: v for k, v in registry.items() if not k.startswith("$")}
        n_src = len(sources_registry.get("sources", {}))
        n_ref = len(sources_registry.get("additional_references", {}))
        print(f"  Provenance registry: {n_src} sources, {n_ref} further references")
        sources_out = OUTPUT_DIR / "sources.json"
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        with open(sources_out, "w") as f:
            json.dump(sources_registry, f, indent=2)
        print(f"  → {sources_out}  ({sources_out.stat().st_size / 1e3:.0f} KB)")
        md_out = INPUT_SOURCES_JSON.parent.parent / "SOURCES.md"
        write_sources_markdown(sources_registry, md_out)
        print(f"  → {md_out}  ({md_out.stat().st_size / 1e3:.0f} KB)")
    else:
        print(f"  ! Provenance registry not found: {INPUT_SOURCES_JSON}")

    # ── Write summary.json ───────────────────────────────────────────────────
    summary_obj = {
        "generated":   datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "total_tracks": len(summaries),
        "date_range": {
            "start": min(s["start"] for s in summaries),
            "end":   max(s["end"]   for s in summaries),
        },
        "years":    sorted({s["year"]           for s in summaries}),
        "months":   sorted({s["month"]          for s in summaries}),
        "regions":  sorted({s["genesis_region"] for s in summaries}),
        # One entry per display variable. The map's colour scale and the
        # intensity filter both read the entry for the active variable, which is
        # what keeps them from ever representing different quantities.
        "display_variables": display_variables,
        # Structural classes present in this build, with counts, so the type
        # filter can render without scanning all tracks client-side.
        "cps_classes": [
            {
                "code":  code,
                "label": CPS_CLASS_LABELS.get(code, code),
                "group": CPS_CLASS_GROUPS.get(code, "Undetermined"),
                "count": count,
            }
            for code, count in sorted(
                Counter(s.get("cps_class") for s in summaries if s.get("cps_class")).items(),
                key=lambda kv: -kv[1],
            )
        ],
        "cps_groups": [
            {"group": g, "count": c}
            for g, c in sorted(
                Counter(s.get("cps_group") for s in summaries if s.get("cps_group")).items(),
                key=lambda kv: -kv[1],
            )
        ],
        "warm_seclusion_count": sum(1 for s in summaries if s.get("warm_seclusion")),
        "tracks": summaries,
        # Provenance, read from data/metadata/sources.json so there is exactly
        # one copy of every DOI in the project.
        "sources": sources_registry,
    }

    out = OUTPUT_DIR / "summary.json"
    with open(out, "w") as f:
        json.dump(summary_obj, f, separators=(",", ":"))
    print(f"\n  → {out}  ({out.stat().st_size / 1e6:.1f} MB)")

    # ── Write details/{year}.json ────────────────────────────────────────────
    for year in sorted(year_data):
        out = DETAILS_DIR / f"{year}.json"
        with open(out, "w") as f:
            json.dump({"year": year, "tracks": year_data[year]}, f, separators=(",", ":"))
        print(f"  → {out}  ({out.stat().st_size / 1e6:.1f} MB)")

    print(f"\n[{datetime.now():%H:%M:%S}] Done. "
          f"{len(summaries)} tracks, {len(year_data)} year detail files.")
    print(f"  Output: {OUTPUT_DIR.resolve()}")
    
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
