#!/usr/bin/env python3
"""
CSV → JSON for the track-only (raw catalogue) cyclones.

Run from the project root:
    python3 scripts/preprocess_raw_tracks.py

Input:
    data/processed/tracks_raw_catalogue.csv
    (generated by scripts/data/ingest_raw_catalogue.py)

Output:
    site/public/data/summary_raw.json         — one entry per raw track
    site/public/data/details_raw/{year}.json  — per-timestep data, columnar

Why these live in separate files from the processed catalogue
-------------------------------------------------------------
There are roughly four times as many track-only cyclones as processed ones.
Folding them into summary.json would take it from ~11 MB to ~35 MB, and that
file is fetched on every single page load. Keeping them apart lets the app load
them only when the processing filter actually asks for them.

Why the detail files are columnar
---------------------------------
A processed timestep is a fat object (LEC + CPS + phase). A raw timestep carries
four numbers. Written as an array of objects, the JSON keys would outweigh the
data several times over. So the raw details use parallel arrays instead:

    {"t0": "1979-01-01T00:00:00",   # first timestep
     "dt": [0, 1, 2, ...],          # hours since t0 (integer, handles gaps)
     "x":  [lon, ...],
     "y":  [lat, ...],
     "v":  [vor42, ...]}

This is roughly 3× smaller than the equivalent array-of-objects and keeps the
gap structure explicit rather than assuming a contiguous hourly series.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import json
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

# ─── Paths ────────────────────────────────────────────────────────────────────
INPUT_CSV = Path("data/processed/tracks_raw_catalogue.csv")
OUTPUT_DIR = Path("site/public/data")
DETAILS_DIR = OUTPUT_DIR / "details_raw"

# ─── Precision ────────────────────────────────────────────────────────────────
COORD_DECIMALS = 2   # ~1 km
VOR42_DECIMALS = 3
# Fewer points than the processed tracks (120): these are context, not the
# object of study, and there are four times as many of them.
MAX_COORDS_PER_TRACK = 60


def downsample(lons, lats, max_pts: int = MAX_COORDS_PER_TRACK):
    n = len(lons)
    if n <= max_pts:
        idx = range(n)
    else:
        step = n / max_pts
        idx = [int(i * step) for i in range(max_pts)]
        if idx[-1] != n - 1:
            idx[-1] = n - 1
    return [[round(float(lons[i]), COORD_DECIMALS),
             round(float(lats[i]), COORD_DECIMALS)] for i in idx]


def main() -> int:
    if not INPUT_CSV.exists():
        print(f"✗ Input not found: {INPUT_CSV}")
        print("\nRun the ingestion first:")
        print("  python scripts/data/download_full_catalogue.py")
        print("  python scripts/data/ingest_raw_catalogue.py")
        return 1

    print(f"[{datetime.now():%H:%M:%S}] Reading {INPUT_CSV.name} …")
    df = pd.read_csv(INPUT_CSV, parse_dates=["date"])
    n_tracks = df["track_id"].nunique()
    print(f"  {len(df):,} rows | {n_tracks:,} track-only cyclones")

    df = df.sort_values(["track_id", "date"]).reset_index(drop=True)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    DETAILS_DIR.mkdir(parents=True, exist_ok=True)

    summaries = []
    year_data: dict = defaultdict(dict)

    print(f"  Processing {n_tracks:,} tracks …")
    for i, (tid, grp) in enumerate(df.groupby("track_id", sort=False)):
        if i % 5000 == 0:
            print(f"    {i}/{n_tracks}")

        grp = grp.reset_index(drop=True)
        first, last = grp.iloc[0], grp.iloc[-1]
        start_dt, end_dt = first["date"], last["date"]
        year = int(start_dt.year)

        summaries.append({
            "id":          int(tid),
            "src":         int(first["source_id"]),
            "year":        year,
            "month":       int(start_dt.month),
            "start":       start_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "end":         end_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "duration_h":  int((end_dt - start_dt).total_seconds() / 3600),
            "genesis_lat": round(float(first["lat"]), COORD_DECIMALS),
            "genesis_lon": round(float(first["lon"]), COORD_DECIMALS),
            "lysis_lat":   round(float(last["lat"]), COORD_DECIMALS),
            "lysis_lon":   round(float(last["lon"]), COORD_DECIMALS),
            "max_vor42":   round(float(grp["vor42"].max()), VOR42_DECIMALS),
            "coords":      downsample(grp["lon"].tolist(), grp["lat"].tolist()),
        })

        # Columnar detail: hours since the first timestep
        dt_h = ((grp["date"] - start_dt).dt.total_seconds() / 3600).round().astype(int)
        year_data[year][str(int(tid))] = {
            "t0": start_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "dt": dt_h.tolist(),
            "x":  [round(float(v), COORD_DECIMALS) for v in grp["lon"]],
            "y":  [round(float(v), COORD_DECIMALS) for v in grp["lat"]],
            "v":  [round(float(v), VOR42_DECIMALS) for v in grp["vor42"]],
        }

    # ── summary_raw.json ──────────────────────────────────────────────────────
    obj = {
        "generated":    datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "total_tracks": len(summaries),
        "date_range": {
            "start": min(s["start"] for s in summaries),
            "end":   max(s["end"] for s in summaries),
        },
        "years":  sorted({s["year"] for s in summaries}),
        "months": sorted({s["month"] for s in summaries}),
        "id_offset": 100_000_000,
        "source": {
            "doi":   "10.17632/kwcvfr52hp.4",
            "label": "Gramcianinov et al. — Atlantic extratropical cyclone tracks "
                     "(ERA5/ExSAt, v4). Different tracking vintage from the "
                     "processed catalogue; IDs are namespaced by id_offset.",
        },
        "tracks": summaries,
    }
    out = OUTPUT_DIR / "summary_raw.json"
    with open(out, "w") as f:
        json.dump(obj, f, separators=(",", ":"))
    print(f"\n  → {out}  ({out.stat().st_size / 1e6:.1f} MB)")

    # ── details_raw/{year}.json ───────────────────────────────────────────────
    total = 0
    for year in sorted(year_data):
        out = DETAILS_DIR / f"{year}.json"
        with open(out, "w") as f:
            json.dump({"year": year, "tracks": year_data[year]}, f, separators=(",", ":"))
        total += out.stat().st_size
    print(f"  → {DETAILS_DIR}/  ({len(year_data)} files, {total / 1e6:.1f} MB total)")

    print(f"\n[{datetime.now():%H:%M:%S}] Done. {len(summaries):,} track-only cyclones.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
