#!/usr/bin/env python3
"""
CSV → JSON pipeline: Generate web-optimized artefacts from consolidated cyclone data.

Run from the project root:
    python3 scripts/preprocess_data.py

Input:
    data/processed/tracks_south_atlantic_consolidated.csv
    (generated by: python scripts/data/run_pipeline.py)

Output:
    site/public/data/summary.json          — one entry per track (metadata + simplified line coords)
    site/public/data/details/{year}.json   — full timestep data per year, loaded on demand by the web app

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Data sources
------------
The consolidated CSV contains data from:
    - Cyclone tracks: Gramcianinov et al. (2019), Mendeley Data, DOI: 10.17632/kwcvfr52hp.4
    - LEC diagnostics: Zenodo, DOI: 10.5281/zenodo.18133432
    - Genesis regions: Gramcianinov et al. (2019), Climate Dynamics
    - Lifecycle phases: Cyclophaser (de Souza et al., JOSS 2025)

Genesis region classification
-----------------------------
The source data includes pre-computed region labels (ARG, LA-PLATA, SE-BR).
For display, these are mapped to more descriptive names.

Lifecycle phase labels
----------------------
Phase labels (incipient, intensification, mature, decay, etc.) are pre-computed
in the source dataset using the Cyclophaser tool:

    de Souza, D. C., da Dias, P. L. S., Gramcianinov, C. B., & de Camargo, R. (2025).
    Cyclophaser: A Python package for detecting extratropical cyclone life cycles.
    Journal of Open Source Software, 10(108), 7363.
    https://doi.org/10.21105/joss.07363

Temporal resolution note
------------------------
    - Track positions (lon, lat, vor42): 1-hourly
    - LEC energetics (Kz, Ke, Ck, Ca, etc.): 3-hourly (NaN at intermediate hours)

This is expected behavior. The JSON output omits NaN energetics values; the web
app displays "LEC diagnostics not available at this timestep" for those hours.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import pandas as pd
import numpy as np
import json
import math
from pathlib import Path
from datetime import datetime

# ─── Paths ────────────────────────────────────────────────────────────────────
# Script must be run from the project root (cyclone_monitor_south_atlantic/).
# Primary input: consolidated CSV generated by scripts/data/run_pipeline.py
INPUT_CSV_CONSOLIDATED = Path("data/processed/tracks_south_atlantic_consolidated.csv")
# Fallback input: legacy raw CSV (for backward compatibility)
INPUT_CSV_LEGACY = Path("data/raw/tracks_SAt_filtered_with_energetics.csv")
OUTPUT_DIR  = Path("site/public/data")
DETAILS_DIR = OUTPUT_DIR / "details"

# ─── Precision ────────────────────────────────────────────────────────────────
COORD_DECIMALS      = 2   # ~1 km — sufficient for trajectory visualisation
VOR42_DECIMALS      = 4
ENERGETICS_DECIMALS = 3
MAX_COORDS_PER_TRACK = 120

# ─── Region name mapping (source data uses short codes) ────────────────────────
REGION_DISPLAY_NAMES = {
    "ARG": "Argentina / Patagonia",
    "LA-PLATA": "SE South America",
    "SE-BR": "SE Brazil Coast",
}


# ─── Genesis Region (fallback for legacy data without region column) ──────────
def assign_genesis_region_fallback(lat: float, lon: float) -> str:
    """
    Classify the cyclone genesis region from its first (genesis) position.
    
    This is a fallback for legacy data that doesn't have the pre-computed
    region column. The consolidated CSV already has region labels.

    Regions approximate the cyclogenesis hotspots identified in:
        Gramcianinov et al. (2019), Climate Dynamics, 53, 4115–4140.
    """
    if lon > 20:
        return "Indian Ocean / Other"
    if lon < -50 and lat < -45:
        return "Argentina / Patagonia"
    if -70 <= lon <= -48 and -45 <= lat <= -25:
        return "SE South America"
    if -55 <= lon <= -35 and -35 <= lat <= -20:
        return "SE Brazil Coast"
    if lon > -35 and -35 <= lat <= -20:
        return "Subtropical South Atlantic"
    if lon > -50 and lat < -45:
        return "Open South Atlantic"
    return "Open South Atlantic"


# ─── Lifecycle Phase (fallback for legacy data without period column) ─────────
def compute_phases_fallback(vor42_series: pd.Series) -> list:
    """
    Heuristic lifecycle phase labels derived from the track's vor42 time series.
    
    This is a fallback for legacy data that doesn't have the pre-computed
    period column. The consolidated CSV already has Cyclophaser phase labels.

    Phase definitions (heuristic approximation):
        incipient        : first 2 timesteps (system just forming)
        intensification  : vor42 increasing, below 85 % of track maximum
        mature           : vor42 ≥ 85 % of track maximum
        decay            : vor42 decreasing, below 85 % of track maximum after peak
        dissipation      : last 2 timesteps
    """
    values = vor42_series.values
    n      = len(values)
    max_v  = float(values.max())
    max_i  = int(np.argmax(values))
    thresh = 0.85 * max_v

    phases = []
    for i, v in enumerate(values):
        if i <= 1:
            phases.append("incipient")
        elif i >= n - 2:
            phases.append("dissipation")
        elif i <= max_i and v < thresh:
            phases.append("intensification")
        elif v >= thresh:
            phases.append("mature")
        else:
            phases.append("decay")
    return phases


# ─── Helpers ─────────────────────────────────────────────────────────────────
def safe_float(value, decimals: int = 3):
    if value is None:
        return None
    try:
        f = float(value)
        if math.isnan(f):
            return None
        return round(f, decimals)
    except (TypeError, ValueError):
        return None


def quantile_label(value: float, thresholds: dict) -> str:
    if value >= thresholds["p95"]:
        return "top 5%"
    if value >= thresholds["p90"]:
        return "top 10%"
    if value >= thresholds["p75"]:
        return "top 25%"
    if value >= thresholds["p50"]:
        return "top 50%"
    return "bottom 50%"


def downsample_coords(lons, lats, max_pts: int = MAX_COORDS_PER_TRACK):
    n = len(lons)
    if n <= max_pts:
        indices = list(range(n))
    else:
        step    = n / max_pts
        indices = [int(i * step) for i in range(max_pts)]
        if indices[-1] != n - 1:
            indices[-1] = n - 1
    return [
        [round(float(lons[i]), COORD_DECIMALS), round(float(lats[i]), COORD_DECIMALS)]
        for i in indices
    ]


# ─── Main ─────────────────────────────────────────────────────────────────────
def main():
    # Determine input file
    if INPUT_CSV_CONSOLIDATED.exists():
        input_csv = INPUT_CSV_CONSOLIDATED
        use_precomputed = True
        print(f"[{datetime.now():%H:%M:%S}] Using consolidated CSV: {input_csv}")
    elif INPUT_CSV_LEGACY.exists():
        input_csv = INPUT_CSV_LEGACY
        use_precomputed = False
        print(f"[{datetime.now():%H:%M:%S}] Using legacy CSV: {input_csv}")
        print("  ⚠ Note: Run 'python scripts/data/run_pipeline.py' for full data with regions/phases")
    else:
        print(f"✗ No input data found!")
        print(f"  Expected: {INPUT_CSV_CONSOLIDATED}")
        print(f"  Or:       {INPUT_CSV_LEGACY}")
        print(f"\nRun data pipeline first:")
        print(f"  python scripts/data/run_pipeline.py")
        return 1
    
    print(f"[{datetime.now():%H:%M:%S}] Reading {input_csv.name} …")
    df = pd.read_csv(input_csv, parse_dates=["date"])
    
    # Handle column names (consolidated has 'lon'/'lat', legacy has 'lon vor'/'lat vor')
    if "lon vor" in df.columns:
        df = df.rename(columns={"lon vor": "lon", "lat vor": "lat"})

    n_tracks = df["track_id"].nunique()
    print(f"  {len(df):,} rows | {n_tracks:,} unique tracks")
    print(f"  Pre-computed region/period: {'Yes' if use_precomputed and 'region' in df.columns else 'No'}")

    df["year"] = (df["track_id"] // 10000).astype(int)
    df = df.sort_values(["track_id", "date"]).reset_index(drop=True)

    # ── Quantile thresholds (track-level max vor42) ──────────────────────────
    print("  Computing intensity quantile thresholds …")
    track_max = df.groupby("track_id")["vor42"].max()
    thresholds = {
        "p25": float(track_max.quantile(0.25)),
        "p50": float(track_max.quantile(0.50)),
        "p75": float(track_max.quantile(0.75)),
        "p90": float(track_max.quantile(0.90)),
        "p95": float(track_max.quantile(0.95)),
    }
    print(f"  vor42 thresholds: { {k: round(v,3) for k,v in thresholds.items()} }")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    DETAILS_DIR.mkdir(parents=True, exist_ok=True)

    # ── Process tracks ───────────────────────────────────────────────────────
    print(f"  Processing {n_tracks:,} tracks …")
    summaries  = []
    year_data: dict = {}

    for i, (tid, grp) in enumerate(df.groupby("track_id", sort=False)):
        if i % 1000 == 0:
            print(f"    {i}/{n_tracks}")

        grp   = grp.reset_index(drop=True)
        first = grp.iloc[0]
        last  = grp.iloc[-1]
        year  = int(first["year"])
        n     = len(grp)

        genesis_lat = round(float(first["lat"]), COORD_DECIMALS)
        genesis_lon = round(float(first["lon"]), COORD_DECIMALS)
        lysis_lat   = round(float(last["lat"]),  COORD_DECIMALS)
        lysis_lon   = round(float(last["lon"]),  COORD_DECIMALS)

        start_dt      = first["date"]
        end_dt        = last["date"]
        genesis_month = int(start_dt.month)
        duration_h    = int((end_dt - start_dt).total_seconds() / 3600)

        # Get genesis region (use pre-computed if available)
        if use_precomputed and "region" in grp.columns:
            region_code = str(first["region"])
            genesis_region = REGION_DISPLAY_NAMES.get(region_code, region_code)
        else:
            genesis_region = assign_genesis_region_fallback(genesis_lat, genesis_lon)
        
        max_vor42      = float(grp["vor42"].max())
        q_label        = quantile_label(max_vor42, thresholds)
        coords         = downsample_coords(grp["lon"].tolist(), grp["lat"].tolist())

        summaries.append({
            "id":             int(tid),
            "year":           year,
            "month":          genesis_month,
            "start":          start_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "end":            end_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "duration_h":     duration_h,
            "genesis_lat":    genesis_lat,
            "genesis_lon":    genesis_lon,
            "lysis_lat":      lysis_lat,
            "lysis_lon":      lysis_lon,
            "genesis_region": genesis_region,
            "max_vor42":      round(max_vor42, VOR42_DECIMALS),
            "quantile":       q_label,
            "coords":         coords,
        })

        # Per-timestep data (loaded on demand via details/{year}.json)
        # Use pre-computed phases if available, otherwise compute heuristically
        if use_precomputed and "period" in grp.columns:
            phases = grp["period"].fillna("unknown").tolist()
        else:
            phases = compute_phases_fallback(grp["vor42"])
        
        timesteps = []
        for j, row in grp.iterrows():
            ts: dict = {
                "date":  row["date"].strftime("%Y-%m-%dT%H:%M:%S"),
                "lon":   round(float(row["lon"]),   COORD_DECIMALS),
                "lat":   round(float(row["lat"]),   COORD_DECIMALS),
                "vor42": round(float(row["vor42"]), VOR42_DECIMALS),
                "phase": phases[j - grp.index[0]],
            }
            # Include all available energetics columns
            for col in ["Az", "Ae", "Kz", "Ke", "Cz", "Ca", "Ck", "Ce", 
                       "BAz", "BAe", "BKz", "BKe", "Gz", "Ge"]:
                v = safe_float(row.get(col), ENERGETICS_DECIMALS)
                if v is not None:
                    ts[col] = v
            timesteps.append(ts)

        if year not in year_data:
            year_data[year] = {}
        year_data[year][str(int(tid))] = {"timesteps": timesteps}

    # ── Write summary.json ───────────────────────────────────────────────────
    summary_obj = {
        "generated":   datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "total_tracks": len(summaries),
        "date_range": {
            "start": min(s["start"] for s in summaries),
            "end":   max(s["end"]   for s in summaries),
        },
        "years":    sorted({s["year"]           for s in summaries}),
        "months":   sorted({s["month"]          for s in summaries}),
        "regions":  sorted({s["genesis_region"] for s in summaries}),
        "quantile_thresholds": {k: round(v, 4) for k, v in thresholds.items()},
        "tracks": summaries,
        # Provenance metadata
        "sources": {
            "tracks": {
                "doi":   "10.17632/kwcvfr52hp.4",
                "label": "Atlantic extratropical cyclone tracks (ERA5/CFSR, 1979–2020)",
            },
            "energetics": {
                "doi":   "10.5281/zenodo.18133432",
                "label": "Semi-Lagrangian LEC diagnostics (1979–2020)",
            },
            "genesis_regions": {
                "doi":   "10.1007/s00382-019-04778-7",
                "label": "Gramcianinov et al. (2019), Climate Dynamics",
            },
            "lifecycle_phases": {
                "doi":   "10.21105/joss.07363",
                "label": "Cyclophaser — de Souza et al. (JOSS 2025)",
            },
        },
    }

    out = OUTPUT_DIR / "summary.json"
    with open(out, "w") as f:
        json.dump(summary_obj, f, separators=(",", ":"))
    print(f"\n  → {out}  ({out.stat().st_size / 1e6:.1f} MB)")

    # ── Write details/{year}.json ────────────────────────────────────────────
    for year in sorted(year_data):
        out = DETAILS_DIR / f"{year}.json"
        with open(out, "w") as f:
            json.dump({"year": year, "tracks": year_data[year]}, f, separators=(",", ":"))
        print(f"  → {out}  ({out.stat().st_size / 1e6:.1f} MB)")

    print(f"\n[{datetime.now():%H:%M:%S}] Done. "
          f"{len(summaries)} tracks, {len(year_data)} year detail files.")
    print(f"  Output: {OUTPUT_DIR.resolve()}")
    
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
