#!/usr/bin/env python3
"""
CSV → JSON pipeline: Generate web-optimized artefacts from consolidated cyclone data.

Run from the project root:
    python3 scripts/preprocess_data.py

Input:
    data/processed/tracks_south_atlantic_consolidated.csv
    (generated by: python scripts/data/run_pipeline.py)

Output:
    site/public/data/summary.json          — one entry per track (metadata + simplified line coords)
    site/public/data/details/{year}.json   — full timestep data per year, loaded on demand by the web app

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Data sources
------------
The consolidated CSV contains data from:
    - Cyclone tracks: Gramcianinov et al. (2019), Mendeley Data, DOI: 10.17632/kwcvfr52hp.4
    - LEC diagnostics: Zenodo, DOI: 10.5281/zenodo.18133432
    - Genesis regions: Gramcianinov et al. (2019), Climate Dynamics
    - Lifecycle phases: Cyclophaser (de Souza et al., JOSS 2025)

Genesis region classification
-----------------------------
The source data includes pre-computed region labels (ARG, LA-PLATA, SE-BR).
For display, these are mapped to more descriptive names.

Lifecycle phase labels
----------------------
Phase labels (incipient, intensification, mature, decay, etc.) are pre-computed
in the source dataset using the Cyclophaser tool:

    de Souza, D. C., da Dias, P. L. S., Gramcianinov, C. B., & de Camargo, R. (2025).
    Cyclophaser: A Python package for detecting extratropical cyclone life cycles.
    Journal of Open Source Software, 10(108), 7363.
    https://doi.org/10.21105/joss.07363

Temporal resolution note
------------------------
    - Track positions (lon, lat, vor42): 1-hourly
    - LEC energetics (Kz, Ke, Ck, Ca, etc.): 3-hourly (NaN at intermediate hours)

This is expected behavior. The JSON output omits NaN energetics values; the web
app displays "LEC diagnostics not available at this timestep" for those hours.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import pandas as pd
import numpy as np
import json
import math
from collections import Counter
from pathlib import Path
from datetime import datetime

# ─── Paths ────────────────────────────────────────────────────────────────────
# Script must be run from the project root (cyclone_monitor_south_atlantic/).
# Primary input: consolidated CSV generated by scripts/data/run_pipeline.py
INPUT_CSV_CONSOLIDATED = Path("data/processed/tracks_south_atlantic_consolidated.csv")
# Fallback input: legacy raw CSV (for backward compatibility)
INPUT_CSV_LEGACY = Path("data/raw/tracks_SAt_filtered_with_energetics.csv")
# Per-cyclone CPS classification (optional).
# PROVENANCE PLACEHOLDER: produced by paper_energy_patterns and copied by hand;
# no Zenodo DOI minted yet. See CPS_PARAMS_FILE in scripts/data/preprocess_data.py.
INPUT_CSV_CPS_CLASS = Path("data/raw/cps_classification_SAt.csv")
# Track-only cyclones from the raw tracking catalogue (optional).
# Generated by scripts/data/ingest_raw_catalogue.py. Only the COUNT is read
# here; the tracks themselves are exported by scripts/preprocess_raw_tracks.py.
INPUT_CSV_RAW = Path("data/processed/tracks_raw_catalogue.csv")
OUTPUT_DIR  = Path("site/public/data")
DETAILS_DIR = OUTPUT_DIR / "details"

# ─── Precision ────────────────────────────────────────────────────────────────
COORD_DECIMALS      = 2   # ~1 km — sufficient for trajectory visualisation
VOR42_DECIMALS      = 4
ENERGETICS_DECIMALS = 3
CPS_DECIMALS        = 2   # B in m, VTL/VTU dimensionless — 2 dp is ample
MAX_COORDS_PER_TRACK = 120

# ─── Region name mapping (source data uses short codes) ────────────────────────
# Canonical codes: ARG, LA-PLATA, SE-BR
# Based on cyclogenesis hotspots from Gramcianinov et al. (2019), Climate Dynamics
REGION_DISPLAY_NAMES = {
    "ARG": "Southeastern Argentina",
    "LA-PLATA": "La Plata River Discharge",
    "SE-BR": "Southeast Brazil",
}

# ─── CPS classification display names ─────────────────────────────────────────
# Per-cyclone structural classification from the Cyclone Phase Space.
# Codes come from cps_classification_SAt.csv → phase_class.
CPS_CLASS_LABELS = {
    "EC":           "Extratropical",
    "SC":           "Subtropical",
    "TC":           "Tropical",
    "ST":           "Subtropical transition (EC→SC)",
    "SD":           "Subtropical decay (SC→EC)",
    "TT":           "Tropical transition",
    "ET":           "Extratropical transition",
    "EC_like":      "Extratropical characteristics (not sustained 36 h)",
    "SC_like":      "Hybrid characteristics (not sustained 36 h)",
    "TC_like":      "Warm-core characteristics (not sustained 36 h)",
    "undetermined": "Undetermined",
    "no_cps_data":  "No CPS data",
}

# Grouping used by the type filter.
#
# TWO RULES, both learned the hard way:
#
#   1. A `*_like` class is NEVER grouped with the class it resembles. Those are
#      CHARACTERISTICS, not identifications: the structure was shown but never
#      sustained for the 36 h gate, and none of the identification guards
#      (genesis band, ocean, warm-seclusion test) was applied to it. Folding
#      `SC_like` into "Subtropical" asserts exactly what the classification
#      refuses to assert — and it is what put 548 unguarded cyclones, 68% of
#      them with genesis outside 20-40 S, under the "Subtropical" filter, plus
#      two `TC_like` at 44 S and 52 S under "Tropical".
#
#   2. Transitions are kept apart by TYPE. EC->SC and SC->EC are opposite
#      pathways and "Transition" hid that.
#
# The source of truth for rule 1 is the `class_kind` / `is_identified` columns of
# cps_classification_SAt.csv; this map must stay consistent with them.
CPS_CLASS_GROUPS = {
    "EC": "Extratropical",
    "SC": "Subtropical",
    "TC": "Tropical",
    "ST": "Subtropical transition",
    "SD": "Subtropical decay",
    "TT": "Tropical transition",
    "ET": "Extratropical transition",
    "EC_like": "Not sustained (<36 h)",
    "SC_like": "Not sustained (<36 h)",
    "TC_like": "Not sustained (<36 h)",
    "undetermined": "Undetermined",
    "no_cps_data": "No CPS data",
}

# Groups that represent an actual identification. The UI can use this to keep
# the descriptive groups visually and semantically separate from the identified
# ones.
CPS_IDENTIFIED_GROUPS = {
    "Extratropical", "Subtropical", "Tropical",
    "Subtropical transition", "Subtropical decay",
    "Tropical transition", "Extratropical transition",
}

# Number of histogram bins for the intensity (vor42) distribution shown in the
# filter panel. 60 keeps the PDF smooth without bloating summary.json.
INTENSITY_PDF_BINS = 60


# ─── Genesis Region (fallback for legacy data without region column) ──────────
def assign_genesis_region_fallback(lat: float, lon: float) -> str:
    """
    Classify the cyclone genesis region from its first (genesis) position.
    
    This is a fallback for legacy data that doesn't have the pre-computed
    region column. The consolidated CSV already has region labels.

    Regions approximate the cyclogenesis hotspots identified in:
        Gramcianinov et al. (2019), Climate Dynamics, 53, 4115–4140.
    """
    if lon > 20:
        return "Indian Ocean / Other"
    if lon < -50 and lat < -45:
        return "Argentina / Patagonia"
    if -70 <= lon <= -48 and -45 <= lat <= -25:
        return "SE South America"
    if -55 <= lon <= -35 and -35 <= lat <= -20:
        return "SE Brazil Coast"
    if lon > -35 and -35 <= lat <= -20:
        return "Subtropical South Atlantic"
    if lon > -50 and lat < -45:
        return "Open South Atlantic"
    return "Open South Atlantic"


# ─── Lifecycle Phase (fallback for legacy data without period column) ─────────
def compute_phases_fallback(vor42_series: pd.Series) -> list:
    """
    Heuristic lifecycle phase labels derived from the track's vor42 time series.
    
    This is a fallback for legacy data that doesn't have the pre-computed
    period column. The consolidated CSV already has Cyclophaser phase labels.

    Phase definitions (heuristic approximation):
        incipient        : first 2 timesteps (system just forming)
        intensification  : vor42 increasing, below 85 % of track maximum
        mature           : vor42 ≥ 85 % of track maximum
        decay            : vor42 decreasing, below 85 % of track maximum after peak
        dissipation      : last 2 timesteps
    """
    values = vor42_series.values
    n      = len(values)
    max_v  = float(values.max())
    max_i  = int(np.argmax(values))
    thresh = 0.85 * max_v

    phases = []
    for i, v in enumerate(values):
        if i <= 1:
            phases.append("incipient")
        elif i >= n - 2:
            phases.append("dissipation")
        elif i <= max_i and v < thresh:
            phases.append("intensification")
        elif v >= thresh:
            phases.append("mature")
        else:
            phases.append("decay")
    return phases


# ─── Helpers ─────────────────────────────────────────────────────────────────
def safe_float(value, decimals: int = 3):
    if value is None:
        return None
    try:
        f = float(value)
        if math.isnan(f):
            return None
        return round(f, decimals)
    except (TypeError, ValueError):
        return None


def quantile_label(value: float, thresholds: dict) -> str:
    if value >= thresholds["p95"]:
        return "top 5%"
    if value >= thresholds["p90"]:
        return "top 10%"
    if value >= thresholds["p75"]:
        return "top 25%"
    if value >= thresholds["p50"]:
        return "top 50%"
    return "bottom 50%"


def load_cps_classification(path: Path) -> dict:
    """
    Load the per-cyclone CPS classification, keyed by track_id.

    Returns {} when the file is absent — CPS is optional and the site degrades
    gracefully (the type filter simply reports no data).

    Each entry carries:
        cls        phase_class code (EC, SC, ST, ...)
        label      human-readable expansion
        group      coarse grouping for the filter UI
        seq        state_sequence, e.g. "EC->SC" (None when absent)
        warm_secl  True when the identification guards rejected at least one
                   run as a Shapiro–Keyser warm seclusion. This is NOT a
                   phase_class: it is a property of the rejected runs, exposed
                   separately because it is scientifically interesting on its own.
    """
    if not path.exists():
        print(f"  ⚠ CPS classification not found: {path}")
        print("    Cyclone type filter will be empty.")
        return {}

    df = pd.read_csv(path)
    print(f"  CPS classification: {len(df):,} cyclones")

    out = {}
    for _, r in df.iterrows():
        code = str(r.get("phase_class", "no_cps_data"))
        n_ws = r.get("n_warm_seclusions", 0)
        try:
            n_ws = float(n_ws)
        except (TypeError, ValueError):
            n_ws = 0.0
        seq = r.get("state_sequence")
        if isinstance(seq, float) and math.isnan(seq):
            seq = None
        group = CPS_CLASS_GROUPS.get(code, "Undetermined")
        out[int(r["track_id"])] = {
            "cls":       code,
            "label":     CPS_CLASS_LABELS.get(code, code),
            "group":     group,
            # Read from the export when present; the map is the fallback so an
            # older CSV still yields a correct flag.
            "identified": bool(r["is_identified"]) if "is_identified" in r
                          and pd.notna(r.get("is_identified"))
                          else group in CPS_IDENTIFIED_GROUPS,
            "seq":       str(seq) if seq is not None else None,
            "warm_secl": bool(n_ws and n_ws > 0),
        }
    return out


def build_intensity_pdf(values: np.ndarray, thresholds: dict) -> dict:
    """
    Histogram of track-level max_vor42, for the intensity filter's PDF display.

    Returns bin edges, the normalised density, and raw counts. The density is a
    proper probability density (integrates to 1 over the value axis), so the
    curve is comparable regardless of bin count.
    """
    counts, edges = np.histogram(values, bins=INTENSITY_PDF_BINS)
    widths = np.diff(edges)
    total = counts.sum()
    density = (counts / total / widths) if total > 0 else np.zeros_like(counts, dtype=float)

    return {
        "bin_edges": [round(float(e), 4) for e in edges],
        "counts":    [int(c) for c in counts],
        "density":   [round(float(d), 6) for d in density],
        "min":       round(float(values.min()), 4),
        "max":       round(float(values.max()), 4),
        "n":         int(values.size),
        # Repeated here so the chart can draw quantile guide lines without
        # cross-referencing another object.
        "quantiles": {k: round(float(v), 4) for k, v in thresholds.items()},
    }


def downsample_coords(lons, lats, max_pts: int = MAX_COORDS_PER_TRACK):
    n = len(lons)
    if n <= max_pts:
        indices = list(range(n))
    else:
        step    = n / max_pts
        indices = [int(i * step) for i in range(max_pts)]
        if indices[-1] != n - 1:
            indices[-1] = n - 1
    return [
        [round(float(lons[i]), COORD_DECIMALS), round(float(lats[i]), COORD_DECIMALS)]
        for i in indices
    ]


# ─── Main ─────────────────────────────────────────────────────────────────────
def main():
    # Determine input file
    if INPUT_CSV_CONSOLIDATED.exists():
        input_csv = INPUT_CSV_CONSOLIDATED
        use_precomputed = True
        print(f"[{datetime.now():%H:%M:%S}] Using consolidated CSV: {input_csv}")
    elif INPUT_CSV_LEGACY.exists():
        input_csv = INPUT_CSV_LEGACY
        use_precomputed = False
        print(f"[{datetime.now():%H:%M:%S}] Using legacy CSV: {input_csv}")
        print("  ⚠ Note: Run 'python scripts/data/run_pipeline.py' for full data with regions/phases")
    else:
        print(f"✗ No input data found!")
        print(f"  Expected: {INPUT_CSV_CONSOLIDATED}")
        print(f"  Or:       {INPUT_CSV_LEGACY}")
        print(f"\nRun data pipeline first:")
        print(f"  python scripts/data/run_pipeline.py")
        return 1
    
    print(f"[{datetime.now():%H:%M:%S}] Reading {input_csv.name} …")
    df = pd.read_csv(input_csv, parse_dates=["date"])
    
    # Handle column names (consolidated has 'lon'/'lat', legacy has 'lon vor'/'lat vor')
    if "lon vor" in df.columns:
        df = df.rename(columns={"lon vor": "lon", "lat vor": "lat"})

    n_tracks = df["track_id"].nunique()
    print(f"  {len(df):,} rows | {n_tracks:,} unique tracks")
    print(f"  Pre-computed region/period: {'Yes' if use_precomputed and 'region' in df.columns else 'No'}")

    df["year"] = (df["track_id"] // 10000).astype(int)
    df = df.sort_values(["track_id", "date"]).reset_index(drop=True)

    # ── Quantile thresholds (track-level max vor42) ──────────────────────────
    print("  Computing intensity quantile thresholds …")
    track_max = df.groupby("track_id")["vor42"].max()
    thresholds = {
        "p10": float(track_max.quantile(0.10)),
        "p25": float(track_max.quantile(0.25)),
        "p50": float(track_max.quantile(0.50)),
        "p75": float(track_max.quantile(0.75)),
        "p90": float(track_max.quantile(0.90)),
        "p95": float(track_max.quantile(0.95)),
        "max": float(track_max.max()),
    }
    print(f"  vor42 thresholds: { {k: round(v,3) for k,v in thresholds.items()} }")

    # ── Intensity PDF (for the filter panel's distribution chart) ────────────
    intensity_pdf = build_intensity_pdf(track_max.to_numpy(dtype="float64"), thresholds)
    print(f"  intensity PDF: {INTENSITY_PDF_BINS} bins over "
          f"[{intensity_pdf['min']}, {intensity_pdf['max']}]")

    # ── Per-cyclone CPS classification ──────────────────────────────────────
    print("  Loading CPS classification …")
    cps_class_map = load_cps_classification(INPUT_CSV_CPS_CLASS)

    # ── Processing level ─────────────────────────────────────────────────────
    # Every cyclone in the consolidated CSV is fully processed (it carries LEC,
    # lifecycle phases and a genesis region — the LEC computation is in fact the
    # filter that produced this catalogue).
    #
    # PLACEHOLDER: the full unfiltered Gramcianinov catalogue
    # (Mendeley DOI 10.17632/kwcvfr52hp.4) is not yet ingested, so no
    # "raw"-level cyclone exists here yet. The flag and the whole downstream
    # filter are already in place, so raw tracks light up the moment they are
    # merged in. See docs/data-documentation.md § Processing levels.
    # Note: deliberately NOT named has_lec — that name is reused as a per-row
    # flag inside the timestep loop below.
    dataset_has_lec = "Kz" in df.columns
    dataset_has_period = "period" in df.columns

    # Count of track-only cyclones. Read from the ingested raw catalogue rather
    # than from summary_raw.json, so the number is correct regardless of which
    # of the two export scripts ran last.
    n_raw_tracks = 0
    if INPUT_CSV_RAW.exists():
        n_raw_tracks = int(
            pd.read_csv(INPUT_CSV_RAW, usecols=["track_id"])["track_id"].nunique()
        )
        print(f"  Track-only cyclones available: {n_raw_tracks:,}")
    else:
        print("  No raw catalogue ingested — 'track only' level will be empty.")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    DETAILS_DIR.mkdir(parents=True, exist_ok=True)

    # ── Process tracks ───────────────────────────────────────────────────────
    print(f"  Processing {n_tracks:,} tracks …")
    summaries  = []
    year_data: dict = {}

    for i, (tid, grp) in enumerate(df.groupby("track_id", sort=False)):
        if i % 1000 == 0:
            print(f"    {i}/{n_tracks}")

        grp   = grp.reset_index(drop=True)
        first = grp.iloc[0]
        last  = grp.iloc[-1]
        year  = int(first["year"])
        n     = len(grp)

        genesis_lat = round(float(first["lat"]), COORD_DECIMALS)
        genesis_lon = round(float(first["lon"]), COORD_DECIMALS)
        lysis_lat   = round(float(last["lat"]),  COORD_DECIMALS)
        lysis_lon   = round(float(last["lon"]),  COORD_DECIMALS)

        start_dt      = first["date"]
        end_dt        = last["date"]
        genesis_month = int(start_dt.month)
        duration_h    = int((end_dt - start_dt).total_seconds() / 3600)

        # Get genesis region (use pre-computed if available)
        if use_precomputed and "region" in grp.columns:
            region_code = str(first["region"])
            genesis_region = REGION_DISPLAY_NAMES.get(region_code, region_code)
        else:
            genesis_region = assign_genesis_region_fallback(genesis_lat, genesis_lon)
        
        max_vor42      = float(grp["vor42"].max())
        q_label        = quantile_label(max_vor42, thresholds)
        coords         = downsample_coords(grp["lon"].tolist(), grp["lat"].tolist())

        # Processing level: "processed" when the cyclone carries the full
        # diagnostic stack (LEC + lifecycle phases). See the PLACEHOLDER note
        # above regarding raw catalogue tracks.
        # A track counts as processed when it carries the diagnostic stack
        # ANYWHERE along its life — not at its first timestep. The lifecycle
        # labeller legitimately leaves `period` empty at the very start of many
        # tracks, so testing only the first row misclassified ~70% of the
        # catalogue as raw.
        track_processed = bool(
            dataset_has_lec
            and dataset_has_period
            and grp["Kz"].notna().any()
            and grp["period"].notna().any()
        )

        cps_info = cps_class_map.get(int(tid))

        entry = {
            "id":             int(tid),
            "year":           year,
            "month":          genesis_month,
            "start":          start_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "end":            end_dt.strftime("%Y-%m-%dT%H:%M:%S"),
            "duration_h":     duration_h,
            "genesis_lat":    genesis_lat,
            "genesis_lon":    genesis_lon,
            "lysis_lat":      lysis_lat,
            "lysis_lon":      lysis_lon,
            "genesis_region": genesis_region,
            "max_vor42":      round(max_vor42, VOR42_DECIMALS),
            "quantile":       q_label,
            "processed":      track_processed,
            "coords":         coords,
        }

        if cps_info:
            entry["cps_class"] = cps_info["cls"]
            entry["cps_label"] = cps_info["label"]
            entry["cps_group"] = cps_info["group"]
            entry["cps_identified"] = cps_info["identified"]
            if cps_info["seq"]:
                entry["cps_seq"] = cps_info["seq"]
            if cps_info["warm_secl"]:
                entry["warm_seclusion"] = True

        summaries.append(entry)

        # Per-timestep data (loaded on demand via details/{year}.json)
        # Use pre-computed phases if available, otherwise compute heuristically
        if use_precomputed and "period" in grp.columns:
            phases = grp["period"].fillna("unknown").tolist()
        else:
            phases = compute_phases_fallback(grp["vor42"])
        
        timesteps = []
        for j, row in grp.iterrows():
            ts: dict = {
                "date":  row["date"].strftime("%Y-%m-%dT%H:%M:%S"),
                "lon":   round(float(row["lon"]),   COORD_DECIMALS),
                "lat":   round(float(row["lat"]),   COORD_DECIMALS),
                "vor42": round(float(row["vor42"]), VOR42_DECIMALS),
                "phase": phases[j - grp.index[0]],
            }
            # Include all available energetics columns
            has_lec = False
            for col in ["Az", "Ae", "Kz", "Ke", "Cz", "Ca", "Ck", "Ce",
                       "BAz", "BAe", "BKz", "BKe", "Gz", "Ge",
                       "RGz", "RGe", "RKz", "RKe"]:
                v = safe_float(row.get(col), ENERGETICS_DECIMALS)
                if v is not None:
                    ts[col] = v
                    has_lec = True
            # Provenance flag: True = original 3-hourly value, False = linearly interpolated.
            # Only included when LEC data is present at this timestep.
            if has_lec:
                raw = row.get("lec_original")
                if raw is not None and not (isinstance(raw, float) and math.isnan(raw)):
                    ts["lec_original"] = bool(raw)

            # ── Cyclone Phase Space ──────────────────────────────────────────
            # Emitted only when the phase-space parameters exist at this
            # timestep (original or interpolated). cps_original mirrors
            # lec_original: True = computed here, False = interpolated.
            cps_b = safe_float(row.get("cps_B"), CPS_DECIMALS)
            if cps_b is not None:
                ts["cps_B"] = cps_b
                ts["cps_VTL"] = safe_float(row.get("cps_VTL"), CPS_DECIMALS)
                ts["cps_VTU"] = safe_float(row.get("cps_VTU"), CPS_DECIMALS)
                cps_cls = row.get("cps_class")
                if isinstance(cps_cls, str):
                    ts["cps_class"] = cps_cls
                # The guarded view: the accepted persistent state covering this
                # timestep, empty when none. cps_class alone is the raw
                # threshold label and carries no persistence and no guards.
                cps_st = row.get("cps_state")
                if isinstance(cps_st, str) and cps_st:
                    ts["cps_state"] = cps_st
                size_km = safe_float(row.get("cps_size_km"), 1)
                if size_km is not None:
                    ts["cps_size_km"] = size_km
                cps_dir = safe_float(row.get("cps_dir"), 1)
                if cps_dir is not None:
                    ts["cps_dir"] = cps_dir
                raw_o = row.get("cps_original")
                if raw_o is not None and not (isinstance(raw_o, float) and math.isnan(raw_o)):
                    ts["cps_original"] = bool(raw_o)

            timesteps.append(ts)

        if year not in year_data:
            year_data[year] = {}
        year_data[year][str(int(tid))] = {"timesteps": timesteps}

    # ── Write summary.json ───────────────────────────────────────────────────
    summary_obj = {
        "generated":   datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "total_tracks": len(summaries),
        "date_range": {
            "start": min(s["start"] for s in summaries),
            "end":   max(s["end"]   for s in summaries),
        },
        "years":    sorted({s["year"]           for s in summaries}),
        "months":   sorted({s["month"]          for s in summaries}),
        "regions":  sorted({s["genesis_region"] for s in summaries}),
        "quantile_thresholds": {k: round(v, 4) for k, v in thresholds.items()},
        # Distribution of track-level max_vor42, used by the intensity filter
        # to draw the PDF, the quantile guide lines and the range slider.
        "intensity_pdf": intensity_pdf,
        # Structural classes present in this build, with counts, so the type
        # filter can render without scanning all tracks client-side.
        "cps_classes": [
            {
                "code":  code,
                "label": CPS_CLASS_LABELS.get(code, code),
                "group": CPS_CLASS_GROUPS.get(code, "Undetermined"),
                "count": count,
            }
            for code, count in sorted(
                Counter(s.get("cps_class") for s in summaries if s.get("cps_class")).items(),
                key=lambda kv: -kv[1],
            )
        ],
        "cps_groups": [
            {"group": g, "count": c}
            for g, c in sorted(
                Counter(s.get("cps_group") for s in summaries if s.get("cps_group")).items(),
                key=lambda kv: -kv[1],
            )
        ],
        "warm_seclusion_count": sum(1 for s in summaries if s.get("warm_seclusion")),
        # Processing levels. Track-only cyclones are NOT in `tracks` — they live
        # in summary_raw.json and are fetched lazily — but their count belongs
        # here so the filter can offer them before that file is loaded.
        "processing_levels": {
            "processed": sum(1 for s in summaries if s.get("processed")),
            "raw":       n_raw_tracks,
        },
        "tracks": summaries,
        # Provenance metadata
        "sources": {
            "tracks": {
                "doi":   "10.17632/kwcvfr52hp.4",
                "label": "Atlantic extratropical cyclone tracks (ERA5/CFSR, 1979–2020)",
            },
            "energetics": {
                "doi":   "10.5281/zenodo.18133432",
                "label": "Semi-Lagrangian LEC diagnostics (1979–2020)",
            },
            "genesis_regions": {
                "doi":   "10.1007/s00382-019-04778-7",
                "label": "Gramcianinov et al. (2019), Climate Dynamics",
            },
            "lifecycle_phases": {
                "doi":   "10.21105/joss.07363",
                "label": "Cyclophaser — de Souza et al. (JOSS 2025)",
            },
            "cyclone_phase_space": {
                # PLACEHOLDER — the CPS dataset is not published yet. Replace
                # `doi` with the Zenodo DOI once the record is minted, and drop
                # `pending` so the About page stops flagging it as unpublished.
                "doi":     None,
                "pending": True,
                "label":   "Cyclone Phase Space classification (Hart 2003 framework) — "
                           "computed by A. Rodriguez (IAG-USP), exported from the "
                           "paper_energy_patterns project. Zenodo DOI pending.",
            },
            "wind100": {
                "doi":   "10.5281/zenodo.19353037",
                "label": "100 m wind statistics per cyclone (1979–2020)",
            },
        },
    }

    out = OUTPUT_DIR / "summary.json"
    with open(out, "w") as f:
        json.dump(summary_obj, f, separators=(",", ":"))
    print(f"\n  → {out}  ({out.stat().st_size / 1e6:.1f} MB)")

    # ── Write details/{year}.json ────────────────────────────────────────────
    for year in sorted(year_data):
        out = DETAILS_DIR / f"{year}.json"
        with open(out, "w") as f:
            json.dump({"year": year, "tracks": year_data[year]}, f, separators=(",", ":"))
        print(f"  → {out}  ({out.stat().st_size / 1e6:.1f} MB)")

    print(f"\n[{datetime.now():%H:%M:%S}] Done. "
          f"{len(summaries)} tracks, {len(year_data)} year detail files.")
    print(f"  Output: {OUTPUT_DIR.resolve()}")
    
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
